### ISSUE TITLE
Unclear license about the derivative fonts

### ISSUE THREAD

**Issue by iology** [LingDong-/chinese-hershey-font#1]
STHeiti and STKaiti are both proprietary. So I think some data doesn't fit the MIT license unless you have been granted the right to include them.

**Comment by LingDong-** [comment]
Hi iology,

Thanks a lot for pointing that out! I'm not familiar with licenses etc., what would you suggest I do?

Currently I'm not including the proprietary fonts themselves in the repo but only data generated from them. Could you recommend a license that fit this situation? Or do I have to remove those data entirely?

Thanks!

**Comment by iology** [comment]
Obviously those two fonts are largely based on the original works, though they look very different. I don't think there is any open source license for **distributing** derivates of proprietary products, even if you clarify it in the document.

So better remove them from the repo. This will also prevent other open source projects from misusing the data. :)

**Comment by LingDong-** [comment]
Thanks. I've now replaced the proprietary fonts with open source alternatives (e6d1866cddbb0bbeed750ab1db641b3d24de0ea8).

**Comment by iology** [comment]
Nice. Those two sources provide very permissive licenses for derivative works.
